##########################################################
#
#                    主目录和环境变量
#
##########################################################
@HOME
{
  title : "${domainName}",
  icon  : "${domainIcon?fas-globe-asia}"
}
@ENV
{
  "OPEN" : "wn.manager",
  "theme" : "${theme?light}",
  "APP_PATH" : "/rs/ti/app:/app",
  "VIEW_PATH" : "/mnt/project/${domain}/view/:/rs/ti/view/",
  "SIDEBAR_PATH" : "~/.ti/sidebar.json:/rs/ti/view/sidebar.json",
  "LOGIN_PAGE" : "${domainLogin?}"
}